# Generated by Django 5.0.6 on 2024-05-08 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
