# Generated by Django 5.0.6 on 2024-05-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='Vancouver', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='logo',
            field=models.ImageField(upload_to='jobs/img/'),
        ),
    ]
