# Generated by Django 5.0.6 on 2024-05-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='projects/img/')),
                ('technologies', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('desc', models.TextField(max_length=200)),
            ],
        ),
    ]
