# Generated by Django 5.0.6 on 2024-05-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='visable',
            field=models.BooleanField(default=False),
        ),
    ]
